version:"3"

services: 
    nginx:
        build: ./nginx/nginx-1.15
        ports: 
            - "80:80"
            - "443:443"
        restart: always
        tty: true
        container_name: nginx1.15
        volumes: 
            - /data/www:/var/www/html
            - /data/logs/nginx:/var/log/nginx
            - /data/docker/config/nginx/conf.d:/etc/nginx/conf.d
            - /data/docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt:/etc/letsencrypt
        networks: 
            - lnmp-networks
    php7:
        build: ./php
        tty: true
        restart: always
        container_name: php7
        volumes: 
            - /data/www:/var/www/html
            - /data/logs/php:/var/log/php
            - /data/docker/config/php/php.ini:/usr/local/etc/php/php.ini
            - /data/docker/config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        depends_on: 
            - nginx
        networks: 
            - lnmp-networks
    redis:
        build: ./redis
        container_name: redis
        tty: true
        restart: always
        volumes:
            - /data/docker/config/redis/redis.conf:/etc/redis/redis.conf
            - /data/redis:/var/lib/redis
            - /data/logs/redis:/var/log/redis
        networks: 
            - lnmp-networks
    mysql:
        build: ./mysql
        container_name: mysql
        tty: true
        restart: always
        ports: 
            - "3306:3306"
        volumes:
            - /data/mysql:/var/lib/mysql
            - /data/docker/config/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
            - /data/logs/mysql:/var/log/mysql
            - /data/mysqlback:/data/mysqlback
        environment: 
            MYSQL_ROOT_PASSWORD: root
        networks: 
            - lnmp-networks
networks: 
    lnmp-networks: