version: '2'
services: 
    nginx:
        build: ./lnmp/dockerfile/nginx/nginx-1.15
        ports: 
            - "8090:8090"
            - "443:443"
        restart: always
        tty: true
        container_name: nginx
        volumes: 
            - ./:/var/www/html
            - ./lnmp/data/logs/nginx:/var/log/nginx
            - ./lnmp/config/nginx1.15/conf.d:/etc/nginx/conf.d
            - ./lnmp/config/nginx1.15/nginx.conf:/etc/nginx/nginx.conf
            - /etc/letsencrypt:/etc/letsencrypt
        networks: 
            - lnmp-networks
    php7:
        build: ./lnmp/dockerfile/php/php7
        tty: true
        restart: always
        container_name: php7
        ports: 
            - "9000:9000"
        volumes: 
            - ./:/var/www/html
            - ./lnmp/data/logs/php:/var/log/php
            - ./lnmp/config/php7/php.ini:/usr/local/etc/php/php.ini
            - ./lnmp/config/php7/www.conf:/usr/local/etc/php-fpm.d/www.conf
        depends_on: 
            - nginx
        networks: 
            - lnmp-networks
    redis:
        build: ./lnmp/dockerfile/redis
        container_name: redis
        tty: true
        restart: always
        volumes:
            - ./lnmp/config/redis/redis.conf:/etc/redis/redis.conf
            - ./lnmp/data/redis:/var/lib/redis
            - ./lnmp/data/logs/redis:/var/log/redis
        networks: 
            - lnmp-networks
    mysql:
        build: ./lnmp/dockerfile/mysql/mysql8.0
        container_name: mysql
        tty: true
        restart: always
        ports: 
            - "3306:3306"
        volumes:
            - ./lnmp/data/mysql:/var/lib/mysql
            - ./lnmp/config/mysql8/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
            - ./lnmp/data/logs/mysql:/var/log/mysql
            - ./lnmp/data/mysqlback:/data/mysqlback
        environment: 
            MYSQL_ROOT_PASSWORD: root
        networks: 
            - lnmp-networks
networks: 
    lnmp-networks: